version: '3'

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3157:3000
    volumes:
      - ./homepage:/app/config
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=192.168.2.13:3157

  jellyfin:
    image: jellyfin/jellyfin
    container_name: Jellyfin
    ports:
      - 8096:8096
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./jellyfin/media:/media

  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - CRON_MIN=3,33
    container_name: FreshRSS
    ports:
      - 4000:80
    volumes:
      - ./freshrss:/config
    restart: unless-stopped

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    environment:
      - TZ=Europe/Amsterdam
    privileged: true
    container_name: HomeAssistant
    ports:
      - 8123:8123
    volumes:
      - ./homeassistant:/config
    restart: unless-stopped
  
  rutorrent:
    image: ghcr.io/linuxserver/rutorrent
    environment:
      - PUID=1000
      - PGID=1000
    container_name: ruTorrent
    ports:
      - 3580:80
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    volumes:
      - ./rutorrent/config:/config
      - ./rutorrent/downloads:/downloads
    restart: unless-stopped