---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Media:
    - FreshRSS:
        icon: freshrss.png
        href: http://192.168.2.13:4000/
        description: A free, self-hostable feed aggregator. FreshRSS is a self-hosted RSS and Atom feed aggregator. It is lightweight, easy to work with, powerful, and customizable.
    - Jellyfin:
        icon: jellyfin.png
        href: http://192.168.2.13:8096/
        description: Jellyfin is the volunteer-built media solution that puts you in control of your media. Stream to any device from your own server, with no strings attached. Your media, your server, your way.

- File management:
    - ruTorrent:
        icon: rutorrent.png
        href: http://192.168.2.13:3580/
        description: ruTorrent is a front-end for the popular Bittorrent client rtorrent.
        widget:
            type: rutorrent
            url: http://192.168.2.13:3580/

- Automation:
    - HomeAssistant:
        icon: home-assistant.png
        href: http://192.168.2.13:8123/
        description: Open source home automation that puts local control and privacy first. Powered by a worldwide community of tinkerers and DIY enthusiasts.