---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Raspberry Pi Dashboard
color: cyan

background:
  image: https://images.unsplash.com/photo-1603486002664-a7319421e133?q=80&w=2142&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 50